sonar.projectKey=genest4p-cpu_qa-auto-engineer-javascript-project-90

sonar.sources=tests
sonar.exclusions=node_modules/**,coverage/**,playwright-report/**,test-results/**,dist/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info